### ISSUE TITLE
Need feedback about the new release?

### ISSUE THREAD

**Issue by itsnauman** [MongoEngine/flask-mongoengine#105]
Hey, if you are facing any kind if issues with the new release or want any new features to be implemented, please let me know :ghost:

**Comment by corydolphin** [comment]
Is it possible to get a new release? There have been 11 pull requests merged since the last release.
https://github.com/MongoEngine/flask-mongoengine/pulls?q=merged%3A%3E%3D2014-08-10+

1. Update index.rst
1. Updated index.rst
1. Make the config easier to override.
1. Fix bug to allow multiple instances of extension.
1. Fix dangerous use self.app in init_app and test refactoring.
1. MongoEngineSessionInterface can now timezone aware dates
1. Support arbitrary primary key fields
1. Update app.py
1. Fix typo
1. Configurable httponly flag for MongoEngineSessionInterface
1. Improve settings parsing: allows and emphasizes MongoDB URI usage in configuration

**Comment by itsnauman** [comment]
Sure, I'll work on it

**Comment by corydolphin** [comment]
Awesome. Let me know if I can do anything to help

**Comment by lafrech** [comment]
I guess this is outdated.

@itsnauman, @corydolphin, let's discuss involvement into the development in @rozza's [Call for Maintainers](https://github.com/MongoEngine/flask-mongoengine/issues/71)
