### ISSUE TITLE
Control to programmer to delay or force query execution

### ISSUE THREAD

**Issue by raun** [MongoEngine/flask-mongoengine#121]
I want to have control to delay or force query execution at a particular set of queries. Right now, I think mongoengine does have a method to force or delay execution of query.

Please refer this : 
http://stackoverflow.com/questions/27941863/control-query-execution-in-mongoengine

**Comment by wojcikstefan** [comment]
Closing this because it's not a Flask-MongoEngine issue. If anything, it should be entertained in MongoEngine. That being said, I don't think it's a good idea anyway. That would hugely complicate the QuerySet code and only add problems, without solving any...

Building on top of your StackOverflow example, if you want the 1st query to fetch the data, do `xobjs = list(X.objects.filter(field1='xyz'))`. Then, instead of writing `xobjs1 = Xobjs.filter(field2='pqr')`, you can simply write `xobjs1 = [obj for obj in xobjs if obj.field2 == 'pqr']`.
