### ISSUE TITLE
QuerySetSelectMultipleField does not allow zeroing out of data

### ISSUE THREAD

**Issue by Ssawa** [MongoEngine/flask-mongoengine#148]
If you try to erase the value of an existing QuerySetSelectMultipleField (field is set to ['foo', 'bar',], you want to set it to []) the `if valuelist` condition in process_formdata prevents you from setting the value to None if it has already been set, as the data field is never changed. (This has nothing to do with validation and the allow_blank flag has no bearing).

Can be fixed pretty easily by adding:

    else:
        self.data = None
at the end, so a complete example would look like:

    def process_formdata(self, valuelist):
        if valuelist:
            if valuelist[0] == '__None':
                self.data = None
            else:
                if not self.queryset:
                    self.data = None
                    return

                self.queryset.rewind()
                self.data = [obj for obj in self.queryset if str(obj.id) in valuelist]
                if not len(self.data):
                    self.data = None
        else:
            self.data = None

**Comment by Ssawa** [comment]
Alternatively I suppose you can instead make sure that the first element of valuelist is set to '__None' when no formdata is present but I've never seen this behavior in any of my ModelSelectMultipleFields

**Comment by lafrech** [comment]
Seems like an easy fix. Everyone agrees with this?

**Comment by losintikfos** [comment]
:+1:

**Comment by lafrech** [comment]
@Ssawa, do you have a test case?

I was about to add your fix, and before I do so, I'like to add a test for this in test/forms.py.

AFAIU, [`process_formdata`](https://wtforms.readthedocs.org/en/latest/fields.html?highlight=process%20formdata#wtforms.fields.Field.process_formdata) is called at form construction, when there is no data in the form. I don't see the case where one *erases the value of an existing QuerySetSelectMultipleField*.

Without your fix, when calling 

    form = DogOwnerForm(MultiDict({'dogs': [],}))

then `form.dogs.data` is `[]`.

With you fix, `form.dogs.data` is `None`. 

- Is it better to have `[]` instead of `None`?

- In which case do you have `['foo', 'bar',]` "in the field" before entering `process_formdata`?

**Comment by Ssawa** [comment]
Hey guys, sorry if I'm a bit spotty on this, I wrote this up a little while ago and I can write up a proper test case when I get home. But we came across this problem primarily while using Flask-Admin so if it helps that's the context I was approaching this from.

If memory serves, `form.dogs.process(formdata, data=_unset_value)` will be called both on the GET request when the form is being created and will initialize dog.data to whatever that field was in mongo, in this scenario the `formdata` parameter is None. But `process` will also be called on the POST request when that form is submitted, this time with the formdata parameter set to whatever was submitted from the html form.

Now process_formdata only gets called if formdata is set, meaning we're dealing with a POST. But _before_ it gets set, WTForm still sets dog.data to whatever was in the database. Meaning if ['foo', 'bar'] is what was in the database when you POSTed, dog.data is already set to ['foo', 'bar'] before entering process_formdata (this is done at https://github.com/wtforms/wtforms/blob/master/wtforms/fields/core.py#L277).

So the problem this issue brings up, perhaps poorly, is that if the formdata for dogs is `[]`, say because somebody wants to clear out the field, `if valuelist:` will be false and dog.data is never touched, the function just returns and the field doesn't change when the model is saved. In my mind it makes no difference at all if the proposed fix does `self.data = None` or `self.data = []` (actually the latter would probably be more idiomatic), it's just a matter of clearing out what self.data was _initially_ set to.

Hope that clears things up a little but if there's any questions please don't hesitate to ask.

**Comment by lafrech** [comment]
Hi.

Thanks for the explanation. I got almost all the pieces, but since it was a bit blurry, I took the easy way and asked... Clearer now.

[WTForms doc](https://wtforms.readthedocs.org/en/latest/crash_course.html#how-forms-get-data) says obj data is used only if no formdata was provided, so I assumed once you're in a POST request, there is formdata and obj is ignored. This is incorrect.

From the code, it is clear that 

- `obj` data is set first then replaced by `formdata` if it exists for the field (which leaves the possibility for an interface to return partial forms, leaving values from `obj` unchanged, if I understand correctly)

- `process_formdata(self, valuelist)` sets data if `valuelist` evaluates to `True`, which is not the case if `valuelist` is `[]`. In this case, `[]` means not data so no issue, but this is problematic in `QuerySetSelectMultipleField`.

If you can send a PR with fix and proper test, that's just perfect.

**Comment by lafrech** [comment]
OK, I can test using

```python
form = DogOwnerForm(MultiDict({'dogs': [],}), dogs=dogs)
self.assertEqual(form.dogs.data, [])  # [] or None
```

This fails without your fix, passes otherwise.

I don't have any opinion concerning `[]` or `None`. The other cases return `None`, so why not `None`. Does it even make any difference? Like, will `None` `$unset` the attribute when saving while `[]` will set it to an empty list? The meaning would be slightly different. Anyway, `None` is fine for me.

**Comment by lafrech** [comment]
I've been playing with this a bit more, adding a few tests and trying to clean up the code in the process.

I'd be happy to get your feedback: https://github.com/Nobatek/flask-mongoengine/commit/7a13945fa4300a9099c35877b5f1e28508a5af59

@losintikfos, do you think I should split this in several commits?

**Comment by losintikfos** [comment]
@lafrech I think one whole commit should be fine as long as regression passes for backward and forward compatibility and Travis is happy.
