### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by brunobelarmino** [MongoEngine/flask-mongoengine#211]
Hey @lafrech @losintikfos,
i was wondering whether [editorconfig](http://editorconfig.org/) and [pylint](https://www.pylint.org) can't help us keeping away problems like:
- space vs tab
- trailing whitespace
- pep8 code conventions

is it a good idea?

**Comment by lafrech** [comment]
Hi @brunobelarmino.

I totally support pylint usage.

I use vi with [syntastic plugin](http://www.vim.org/scripts/script.php?script_id=2736) to check the code with pylint when I write a file.

I also have a script that does a few useful modifications (trailing whitespace, tabs -> 4 spaces, AltGr+space -> space).

And I never did it before, but there are ways to integrate pylint to GItHub to check commits, probably through Travis.

From a quick search:

https://github.com/xenserver/xenserver-build-env/commit/274423f2843b913ca2a20d88c9ba96d36fd0f923
http://stackoverflow.com/questions/12450348/how-to-integrate-any-python-lint-with-github-commit-status-api
http://stackoverflow.com/questions/9799209/enforcing-pep-8ish-formatting-in-github-commits

Total perfection is probably unreachable under pylint, unless we remove a lot of rules, so we should make sure we won't get a failed status under Travis just because of pylint. What we want is not a boolean status, but rather a mark (/100) and ideally a readable report that points the warnings / errors that were introduced.

I don't know if this is readily available or if it needs tweaking a bit with the configuration.

**Comment by lafrech** [comment]
BTW, @brunobelarmino, if you're interested in further development of flask-mongoengine, and maybe join the team, please show up in https://github.com/MongoEngine/flask-mongoengine/issues/71.

**Comment by brunobelarmino** [comment]
thanks @lafrech for your tip! :grinning:

**Comment by lafrech** [comment]
I think we can close this.

flask8 is not added to Travis (https://github.com/MongoEngine/flask-mongoengine/pull/270) and will report code style issues.

It is up to the dev to chose his own tools to check code style while coding.
