### ISSUE TITLE
docs link are broken

### ISSUE THREAD

**Issue by sibeliusseraphini** [MongoEngine/flask-mongoengine#224]

**Comment by lafrech** [comment]
Which links?

Are you referring to https://github.com/MongoEngine/mongoengine/issues/1285?

This works: https://flask-mongoengine.readthedocs.io/en/latest/

**Comment by sibeliusseraphini** [comment]
this one https://flask-mongoengine.readthedocs.org on README.md

**Comment by lafrech** [comment]
There must be some magic, here, because when I click your link several times I get two different results:

- https://flask-mongoengine.readthedocs.io/en/latest/
- http://docs.mongoengine.org/projects/flask-mongoengine/en/latest/

Only the first works. The second does not.

**Comment by lafrech** [comment]
It seems the URL is redirected to https://flask-mongoengine.readthedocs.io/en/latest/ and it is working fine AFAICT.

Anyway, I sent a PR with a fix to the README to use .io instead of .org: https://github.com/MongoEngine/flask-mongoengine/pull/226.

I think this closes this issue. Otherwise, please reopen.

Thanks.

**Comment by sibeliusseraphini** [comment]
thanks
