### ISSUE TITLE
pip still has old version 0.8.2

### ISSUE THREAD

**Issue by robertaistleitner** [MongoEngine/flask-mongoengine#295]
On github there's already a [0.9.0 release](https://github.com/MongoEngine/flask-mongoengine/releases/tag/v0.9.0), which is not available from [python pip](https://pypi.python.org/pypi/flask-mongoengine/).

**Comment by lafrech** [comment]
Thanks @robertaistleitner for the feedback.

@wojcikstefan could it be because the automatic PyPI upload works only if the build passes?

I can't push manually: I don't have the privileges on PyPI.

(We should be [publishing a 0.9.1 soon](https://github.com/MongoEngine/flask-mongoengine/issues/294#issuecomment-277965078), hopefully with build passing and automatic PyPI upload will work.)

**Comment by BillRainford** [comment]
I've been hitting this as well and eagerly waiting on that 0.9.1 release.

**Comment by wojcikstefan** [comment]
@robertaistleitner @lafrech @BillRainford sorry about the delay on this one. I just pushed out a dummy commit that should trigger the deployment to PyPI. If that doesn't work, I'll investigate further. Appreciate your patience!

**Comment by wojcikstefan** [comment]
> dummy commit that should trigger the deployment to PyPI.

Nevermind, we only publish to PyPI upon tagged commits (i.e. when you make a GitHub release).

I uploaded v0.9.0 manually and just released v0.9.1. Will make sure Travis deploys it properly.

**Comment by lafrech** [comment]
Apparently, it didn't.

**Comment by wojcikstefan** [comment]
Thanks @lafrech! The problem was caused by the `branches` setting in `.travis.yml` which prevented tags from being built, and which I removed in 5c947c7. A dummy v0.9.2 release just started building:

<img width="850" alt="screen shot 2017-02-16 at 6 06 45 pm" src="https://cloud.githubusercontent.com/assets/1718372/23045473/b8a2b9d2-f472-11e6-95e1-29be09a66748.png">

**Comment by wojcikstefan** [comment]
https://travis-ci.org/MongoEngine/flask-mongoengine/jobs/202436692#L553 worked. Thanks guys for your help and your patience!
