### ISSUE TITLE
unit tests throw extension already initialized

### ISSUE THREAD

**Issue by anilj** [MongoEngine/flask-mongoengine#297]
Perhaps this is related to:
https://github.com/MongoEngine/flask-mongoengine/issues/264

I get an error "Exception: Extension already initialized" from flask_mongoengine when I try to configure unit tests.

This works:
app.py:
```
def initialize_app(config='Devel'):
  app = Flask(__name__)

  # Import config
  app.config.from_object(Config.choose(config))

  # Extensions
  db.init_app(app)
```

tests.py:
```
from app import initialize_app

class BaseTest2(TestCase):
  def create_app(self):
    app = initialize_app('Test')
    return app

  def setUp(self):
    pass

  def tearDown(self):
    db = _get_db()
    db.client.drop_database(db)

class TestFrontend(BaseTest2):
  def test_1(self):
    pass

  def test_2(self):
    pass
```

But as soon as I move the Flask app building to a global, it breaks with that exception about Extensions already initialized.
```
app = Flask(__name__)

def initialize_app(config='Devel'):
  ...
```

I think I would prefer to have the global Flask app defined but I can't seem to get the tests to work. For now, I will switch to moving the Flask() to inside initialize_app(). It just seems a bit weird in using it.

Isn't it normal for unit tests to re-initialize the same extension?

**Comment by lafrech** [comment]
Our application has a `create_app` application factory that instantiates app and calls `extension.init_app(app)` for every extension. This factory is called in a `run.py` file we use to run the app, and it is also called in the test setup method. In other words, `app` is a new instance for each test.

I'm not saying this is the only way to go, but that's how I do and I probably picked this pattern from someone more knowledgeable on the Internet.

I'm not sure this is specific to `flask-mongoengine`. Is it the only extension complaining about multiple registrations?

You may want to reconsider your initialization method. Here's mine:

```python
from . import extensions
from . import modules

def create_app(flask_config=DEFAULT_CONFIG, config_class=None, **kwargs):

    app = Flask('My app', **kwargs)

    # A config class can be passed "manually" (typically for tests)
    # The general use case is "config_class is None"
    if config_class is None:
        config_class = os.getenv('FLASK_CONFIG', flask_config)
        config_class = CONFIGS[config_name]

    app.config.from_object(config_class)

    extensions.init_app(app)
    modules.init_app(app)

    return app
```

In extensions module, `init_app` calls `init_app` on each extension we use (unless disabled in configuration). And we have the same pattern for each module of our application.

In fact, this is more or less what you do in your working example, except it should be called `create_app` rather than `initialize_app`. I don't know what you dislike about it. I believe it is fine.

**Comment by anilj** [comment]
Why does it need to be called create_app? I actually do exactly that (to make it work), create the Flask app and return it in the initialize_app. 

What looked weird for me was using the Flask-script (manager) extension, which doesn't have a init_app, so I have to pass in the app to the constructor:

```
from app import initialize_app

manager = Manager(initialize_app())

@manager.command
def shell(config='Devel'):
  """Initalize and start an interactive shell"""
  app = initialize_app(config)
```

It looked weird that I have to call initialize_app() two times for the manager to function. For now, I will stick to this to unblock me.

But it does seem like this is the only extension that does this. The other extensions don't have an explicit check in the init_app() to see if the extension was already registered AFIK... which is the exception I was getting as noted.

**Comment by lafrech** [comment]
> Why does it need to be called create_app?

Sorry if I was unclear. Indeed, the name does not make any difference. I was just saying that your example seemed perfectly fine to me and I would keep it as it is, just changing the name to `create_app` since this is what it does.

> The other extensions don't have an explicit check in the init_app() to see if the extension was already registered AFIK... which is the exception I was getting as noted.

OK. I don't know enough extensions to tell. If flask-mongoengine is the only extension with this restriction, maybe we could try to address that. But I'm not sure how useful that would be. Creating a new app for each test seems easy enough.

I don't know Flask-script, so I won't be of much help with your specific issue. You might find this discussion interesting, though: https://github.com/smurfix/flask-script/issues/122

**Comment by insspb** [comment]
test moved to pytest,  should not be a problem anymore #371
