### ISSUE TITLE
Is the flask-mongoengine project still alive?

### ISSUE THREAD

**Issue by blatoo** [MongoEngine/flask-mongoengine#349]
Hi flask-mongoengine team, 

since the last commit is already nearly one year past. Will this library still continue to be updated? Or the project is closed?

Thanks very much for the great work!

**Comment by ufo911** [comment]
I also need to know, there are some features supported in mongoengine and not in flask-mongoengine

**Comment by pipozzz** [comment]
Hi guys,

is this project still maintained?

Thanks

**Comment by ufo911** [comment]
@touilleMan

**Comment by touilleMan** [comment]
Hi guys,
I don't use mongoengine any more so no clues about this.
However if you want to help support the project, I'm sure you'll be welcome in the mongoengine organization (I don't have admin rights myself) ;-)

**Comment by lafrech** [comment]
I don't use mongoengine anymore either.

I do have the admin rights to add new members to the team, although I'd rather leave that decision to someone in the team who is still involved.

@MongoEngine/flask-mongoengine anybody still here?

**Comment by vantastic** [comment]
> Hi guys,
> I don't use mongoengine any more so no clues about this.
> However if you want to help support the project, I'm sure you'll be welcome in the mongoengine organization (I don't have admin rights myself) ;-)

@touilleMan Do you use an alternative to flask_mongoengine? Which one?

**Comment by mvellasco** [comment]
@mol1narius I was looking for an alternative and I've found(flask-pymongo)[https://github.com/dcrosta/flask-pymongo] it isn't as sophisticated as mongoengine, but it is really helpful, with a low footprint, and easy to extend as well(if you need to).

**Comment by insspb** [comment]
@blatoo @ufo911 @pipozzz @mvellasco @mol1narius 
@lafrech @touilleMan 
Several days ago i get permission to make commits to master. In next month or so I will update code to modern paterns, and update CI/CD as well.
Then some new features will be implemented. 
Next version will not support python <3.6 as it is too hard to maintain old versions that are already EOL or near it (like python 3.5)
You are welcome to share your thoughts and PRs, they will be reviewed.
The maximum expected time is 1 month for PR review, as it is not commercial work for me, but this is maximum. Usually much less, as this project is used in our production.

**Comment by mol1narius** [comment]
@insspb Thank you for your notice and the effort to keep this repo alive.

When I evaluated this repo, I saw a great potential in the integration of wtform. First, this seemed very promising since this was a feature I was looking for. After some testing, I found that the integration was quit challenging. It took me quit a while to find which arguments go into the Model for mongo and which are used for wtforms. This was partly because I was new to the mongo and wtforms but also because the documentation of this repo lacks some parts.

Finally, I decided to keep the two part (mongoengine and flask) separate and use their corresponding libraries.
