### ISSUE TITLE
Form does not validate on submit. No data is sent on submission.

### ISSUE THREAD

**Issue by zberwaldt** [MongoEngine/flask-mongoengine#379]
I'm encountering an issue with a form I've created off of a model in rudimentary app I've been building. Every time I submit the form, No data is sent with the generated wtform and it doesn't validate even though I've met the requirements. 

the model:
```python
class Content(db.Document):

    meta = {
        'collection': 'user_content',
    }

    title = db.StringField('Title', max_length=50, required=True, validators=[InputRequired(message=u'Missing title.')])
    text = db.StringField('Text')
    author = db.StringField('Author', max_length=50)

    def __repr__(self):
        return "<Content '{}'>".format(self.title)
```
The route: (in flask)
```python
@app.route('/', methods=['GET', 'POST'])
def home():

    form = ContentForm()
    content = Content.objects.all()
    if form.is_submitted():
        print("Form successfully submitted")

    # For some reason: form.validate_on_submit() or form.validate() never
    # evaluate to true.
    if request.method == 'POST' and form.validate_on_submit():
        print('Success!')
        new_content = Content()
    
        new_content.title = "a title"
        new_content.text = "some text"
        new_content.author = "Kevin."
        
        new_content.save()
        flash('Content added', 'info')
        return redirect(url_for('.home'))

    return render_template('home.html', form=form, content=content)
```

I don't know if this is enough information, let me know If: 
a.) you need more info. 
b.) I'm in the wrong place.

**Comment by insspb** [comment]
@zberwaldt thank you for report and excuse for long answer. 

The problem is in how you set up fields, as you use arguments, and we use some monkeypatching (in version before 2.0.0) you silently created additional Regex requirement. 

You can discover it, if you check object details.

![Screenshot_20220720_124210](https://user-images.githubusercontent.com/1916759/179951734-79342d7e-85f1-43bd-9269-2eaf6646c51d.png)

Seems that you followed FlaskWTF Forms or something like this to setup, but first argument translated to db ``regex`` option, and this option translated to such filter in form. In version 2.0.0 we will restrict arguments passing to exclude such problems, that can be hard to discover (#481)
